import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "My Awesome Site",
  description: "Generated by Next.js & Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
